apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smpdfgen
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 12
    scalingStrategy:
      cpu:
        thresholdPercentage: 85
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  leaderElection: false
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2560Mi
    requests:
      cpu: 100m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: syfosmsak
          namespace: teamsykmelding
          cluster: prod-gcp